version: "3.8"

services:

  node1:
    build: ./storage_node_service
    container_name: node1
    ports:
      - "8001:8000"

  node2:
    build: ./storage_node_service
    container_name: node2
    ports:
      - "8002:8000"

  node3:
    build: ./storage_node_service
    container_name: node3
    ports:
      - "8003:8000"